/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rahnema.tumaj.bid.backend;

import org.junit.Test;
import static org.junit.Assert.*;

public class BidApplicationTest {
    @Test public void testAppHasAGreeting() {
        BidApplication classUnderTest = new BidApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
